---
# here comes env checking

- name: check mandatory vars
  debug: msg="Cheking {{ item | mandatory  }} "
  tags: check
  with_items:
     - "{{gce_lb_name}}"
     - "{{gce_region}}"
     - "{{gce_service_account_email}}"
     - "{{gce_pem_file}}"
     - "{{gce_project_id}}"
     - "{{gce_zone}}"
     - "{{gce_lb_member_inventory_group}}"
     - "{{gce_lb_protocol}}"

- name: check pem file is present
  local_action: stat path="{{playbook_dir}}/{{gce_pem_file}}"
  register: pem_file_stat
  ignore_errors: True
  tags: check

- fail: msg="Pem file {{ gce_pem_file }} not found in playbook directory"
  when: pem_file_stat.stat.exists == false
  tags: check
